server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    secret-key: you_secret_key
